# Site settings
title: HackyHour@Auckland
email: eresearch@auckland.ac.nz
url: https://uoa-eresearch.github.io/HackyHour
description: "Building a community to help share the latest tools and research best practice. Also hacking on bits of code and data."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright:  eResearch @ Auckland
  location: Centre for eResearch - The University of Auckland
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/uoahackyhour
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/uoa-eresearch
  - title: tumblr
    url: http://uoahackyhour.tumblr.com

# Postal address (add as many lines as necessary)
address:
  - line: Centre for eResearch
  - line: University of Auckland

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
